### ISSUE TITLE
"Cannot read property 'indexOf' of undefined"

### ISSUE THREAD

**Issue by Mactub07** [ccm-innovation/react-native-scrolling-menu#3]
when click on menu item , show red screen "Cannot read property 'indexOf' of undefined"
ver RN 0.28
Platform IOS

**Comment by bradbyte** [comment]
@Mactub07 thanks for checking out the repo and posting your issue. Can you provide the code you're using to call the menu?

**Comment by mikeahirsch** [comment]
@Mactub07 This has been fixed in v0.1.1. Thank you for your feedback.
