### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by RatFou** [ccm-innovation/react-native-scrolling-menu#5]
Hi, great component!
I'm trying to remove the horizontal scrollbar, but I can't.

I added 
`showsHorizontalScrollIndicator={false}
showsVerticalScrollIndicator={false}`
in the `<ScrollView>` but nothing happened.

Do you have any idea how to remove the scrollbar?

**Comment by bradbyte** [comment]
@thathirsch any ideas?

**Comment by bradbyte** [comment]
@RatFou it doesn't look like any extra props are passed down to the underlying `ScrollView`. @thathirsch any objections if that was changed?

**Comment by mikeahirsch** [comment]
@RatFou I assume you forked the repo or just made your own component in your app using this code? If so, adding those props to the ScrollView component should do the trick. If it's not working I'd consult with Google.

**Comment by mikeahirsch** [comment]
@bradbumbalough No, we aren't passing down those props to the underlying ScrollView.

**Comment by bradbyte** [comment]
@thathirsch right. I mean should we go ahead and add the rest of the props to the `ScrollView` so this would be supported?

**Comment by RatFou** [comment]
Hi, thanks for your answers. I added `showsHorizontalScrollIndicator: false,` when the scrollview is created and everything id fine now.
